version: '3.8'

services:
  app:
    image: fooddiaryappserver:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fooddiary
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: wcttSKhmw10112023
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: fooddiary
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wcttSKhmw10112023
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
